version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: mcp-prompt-postgres
    environment:
      POSTGRES_DB: mcp_prompts
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mcp_password_123}
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_prompts"]
      interval: 10s
      timeout: 5s
      retries: 5

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-prompt-server
    ports:
      - "8080:8080"  # Expose HTTP port
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mcp_prompts
      - POSTGRES_USER=mcp_user
      - POSTGRES_PASSWORD=mcp_password_123
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "-f", "mcp-proxy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Create ./secrets/postgres_password.txt with custom password
# If not provided, uses default password: mcp_password_123

volumes:
  postgres_data: 