version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: mcp-prompt-postgres
    secrets:
      - postgres_password
    environment:
      POSTGRES_DB: mcp_prompts
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_prompts"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt  # Not in version control

volumes:
  postgres_data: 